### ISSUE TITLE
Owner validation

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#115]
Per our readme: https://github.com/xmidt-org/argus#create-individual-item---storebucketid-endpoint

The optional owner header input is a "Free form string to identify the owner of this object."
"The value of this header will be bound to a new record, which would require the same value passed in a X-Midt-Owner header for subsequent reads or modifications. This in effect creates a secret attribute bound to the life of newly created records.

When an owner value is specified, how should we go about validating it? 

If we want to follow the same procedure we already have for validating bucket names we would have: 
- A configurable regular expression to match owner values. 
- When configuration is not provided, we'd default to a reasonable value.
Here's one option:
    - Between 10 and 64 characters
    - At least two of: numbers, special characters from the set [!@#$&*] and upper case letters
    - At least three of: lower case letters 

The regex would be 
```
^(?=.*[A-Z].{2,})(?=.*[0-9].{2,})(?=.*[!@#$&*].{2,})(?=.*[a-z].{3,}).{10,64}$
```

I'm open for suggestions.

**Comment by johnabass** [comment]
Length validation makes sense.  Do we need any other validation?  Can we just allow any string that is permitted within an HTTP header?  That's basically just 7-bit ASCII.

**Comment by joe94** [comment]
We can leave the validation configurable for folks who want to impose their own format but for the default, we could just enforce those length requirements 👍
