### ISSUE TITLE
Don't use `webpa-common/logging`

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/argus#123]
https://pkg.go.dev/github.com/xmidt-org/webpa-common@v1.11.4/logging

The logging package being used in argus is deprecated and ideally we should remove it from argus.

**Comment by joe94** [comment]
For example, calls like this one:
```
logging.Error(s.logger).Log(logging.MessageKey(), "failed to close iter ", "bucket", key.Bucket, "id", key.ID)
```
can be replaced with 
```
level.Error(s.logger).Log(xlog.MessageKey(), "failed to close iter ", "bucket", key.Bucket, "id", key.ID)
```
