### ISSUE TITLE
Clarification on source of owner

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#131]
So far, I've been assuming the single source of item owners is an http header. In our [readme](https://github.com/xmidt-org/argus#create-individual-item---storebucketid-endpoint) it says it would also be part of the input payload as an attribute. 
Is this a typo or do we want this in the payload as well and have it cross checked with the header?

**Comment by JC000** [comment]
That's a bug in the README resulting from the evolution of the "owner" feature.  Since we have defined "owner" akin to a secret, it should never be present in the body, in either read or write operations.
