### ISSUE TITLE
Chrysom config doc and validation

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#138]
1) To stay consistent with other repos such as [github.com/xmidt-org/ancla](url), we should make the metrics provider optional https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L104
The default should be the discard provider.

2) The listener bucket should also be optional and default to `webhooks` https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L116

3) We should explicitly state that `PullInterval` is optional and that it defaults to 5 seconds
https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L113

4) Logger is also optional and default to a no op logger
https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L106

**Comment by kristinaspring** [comment]
Just to confirm, the only things required for the Client with this change will be the address (aka argus URL).  What about the Listener?
https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L110

It's not documented as Optional, but it seems optional.

**Comment by kristinaspring** [comment]
I've thought about this more, and I agree with most of this, but I think the bucket should stay required, without a default. Also, it's only really required when a Listener is provided, so it's kind of optional? Required, but only sometimes? 😅 

Also, this might be its own issue, should we group listener related configuration? Then all listener-related config is optional kind of...together.

**Comment by joe94** [comment]
Any reason why we couldn't make the bucket optional default to "webhooks"? Since we're making the bucket apply to both regular and listening operations with #139, I figured it's ok to leave the bucket as a general (not listener only) optional config to Argus.

**Comment by joe94** [comment]
Yeah, I think we should group all the configuration values that apply to the listener only.

**Comment by kristinaspring** [comment]
Even though we are currently using argus for webhooks, it could really be used for anything, right? Are there other webhook-specific defaults now? If not, I would prefer not to add any.  If there are, then default to "webhooks" seems fine. 🙂

**Comment by joe94** [comment]
Great point. I don't think we're using webhooks specific defaults anywhere else in Argus. I'm good with making a bucket required then 👍
