### ISSUE TITLE
Add optional OpenTelemetry tracing

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#165]
We should try and stay consistent with how the feature is configured and set up. Here's an example from Tr1d1um: https://github.com/xmidt-org/tr1d1um/issues/203

Since Argus and Themis are both using the `uber/fx` lib, they're likely to share more in common.

**Comment by joe94** [comment]
A version of Themis with instrumentation has been published. https://github.com/xmidt-org/themis/issues/74 contains the implementation details that we should follow for Argus.

**Comment by utsavbatra5** [comment]
Hi @joe94 I have opened a PR for argus https://github.com/xmidt-org/argus/pull/170

**Comment by joe94** [comment]
Fixed in #170

**Comment by Sachin4403** [comment]
HI @joe94 

When you guys are planning to release the argus version with automatic instrumentation of candlelight?

**Comment by Sachin4403** [comment]
@joe94, We were blocked on that but now we are continuing with DB, so we unblocked now. It will be helpful if you can release argus.

**Comment by joe94** [comment]
@Sachin4403, sounds good. I'll release it ASAP today.

**Comment by Sachin4403** [comment]
Thanks @joe94 for releasing argus/v0.3.15
