### ISSUE TITLE
Documentation: storing an item without a x-midt-owner will prevent overwriting with a request with an owner

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#166]
If you add an item (PUT) without a x-midt-owner, then subsequently send a 2nd request (PUT) with a x-midt-owner, the updated request will be rejected.

**Comment by joe94** [comment]
I ran a few tests and this behavior does not apply to requests that run in admin mode. This only applies to non-admin requests in which the owner provided in the second request does not match the owner (whose value is the empty string) of the existing item
