### ISSUE TITLE
TTL for stored item not decreasing

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#193]
The record ttl does not decrease.
1. PUT an item to argus with a  TTL of 300.
2. GET the item, the TTL will be 300
3. wait 30 seconds, and GET the item.  The TTL will still be 300.
expected: it would decrease.

**Comment by joe94** [comment]
After digging a bit into this, I found that the issue is isolated to the in-memory store implementation. The yugabyte and the dynamodb implementations seem to be working fine.
