### ISSUE TITLE
bucket names are not sanitized

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#28]
argus will accept many different characters as bucket names.  For example \\ is considered valid.  
e.g
curl -H "Authorization:$basicauth" 'https://$argusserver:443/api/v1/store/\\' -d '{"identifier" : "payload3","data":{"qa3":"qa3"},"ttl":300}' -i -X PUT
returns:
{"bucket":"\\\\","id":"tPO9_4P78gMPbmDA6_XxhJRrhIVUguLgK0Mgf0ztHrc"}

Also note that the bucket name returned is \\\\ instead of \\
To retrieve you still need \\ as in
curl -X GET -i -H "Authorization:$basicauth" 'https://$argusserver:443/api/v1/store/\\'

**Comment by joe94** [comment]
What constraints should we place for bucket name validation?

**Comment by kristinaspring** [comment]
Alphanumeric plus `-` and `_`?

**Comment by j-mai** [comment]
Maybe we can follow some of the aws s3 bucket name [rules](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)?

**Comment by JC000** [comment]
Nice catch.

**Comment by schmidtw** [comment]
Whichever we choose, there should be an enforcement step.  The S3 rules are move involved than checking this regex: `/[a-zA-Z0-9_-]+/`.

**Comment by joe94** [comment]
I like some of the S3 bucket rules as they would make bucket names easier to parse/read. I'm thinking of having the enforcing step have the rules:
- Bucket names must be between 3 and 63 characters long.
- Bucket names can consist only of lowercase letters, numbers and hyphens (-).
- Bucket names must begin and end with a letter or number.
