### ISSUE TITLE
argus returns 500 error for bad request

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#29]
Our testing configuration uses dynamodb.  I submitted a nested json object (512 deep) to argus.  This results in a 500 error as dynamodb supports up to 32 deep nested objects.
The error returned is: 
``
Request Failed:  "ValidationException: Nesting Levels have exceeded supported limits: Attributes in the item have nested levels beyond supported limit\n\tstatus code: 400, request id: [redacted]"
``
dynamodb returns a 400, we should probably return a 400 to the user rather than a 500 as this is an error in the user request.

**Comment by joe94** [comment]
We should add a configurable validator for the depth of the item data field. By default, it should be dynamodb's [limit](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html) which is 32.

**Comment by joe94** [comment]
Related to #30

**Comment by joe94** [comment]
One implementation for this solution would be to perform a recursive check on all keys of the json and mark the request invalid if the depth goes beyond the limit at any branch.

**Comment by kristinaspring** [comment]
In addition to doing our best effort to validate input before trying to insert it into the database, we can check the errors we receive from dynamodb:
https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/#Error
Doing a type assertion to get this interface allows us to check the Code, which are basically sentinel errors that aws provides:
https://github.com/aws/aws-sdk-go/blob/v1.37.21/service/dynamodb/errors.go#L9

I think this example falls under this error code:
https://github.com/aws/aws-sdk-go/blob/v1.37.21/service/dynamodb/errors.go#L282
I'm not sure if we can return 400 for any `ErrCodeTransactionCanceledException`.
