### ISSUE TITLE
argus merges the data fields for duplicate names

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#60]
Currently, Argus accepts json payloads with duplicate object names e.g. 
`{"identifier" : "minimal0","data": {"minnie":"mouse"},"ttl":300,"identifier" : "minimal1","data": {"mickey":"mouse"},"ttl":600}`

This is what's stored:
`{"identifier":"minimal1","data":{"mickey":"mouse","minnie":"mouse"},"ttl":572}`

Non-unique names appeared to be allowed in json, but this results in inconsistent behavior.  The value for identifier & ttl are replaced by the later duplicate, but data field values are merged.

**Comment by johnabass** [comment]
This really isn't a bug per se.  It's how the `encoding/json` package behaves.  Incidentally, this behavior is common:  most languages and platform handle duplicate fields by taking the last occurrence of that field in the stream.  The JSON RFC is silent on how to unmarshal messages with duplicate fields.  This is just the most common choice made by API and framework engineers.

Any way we would try to fix this in a server would result in inconsistent behavior from someone's point of view.  Arguably, this is a client bug.  It would be nice for our server software to detect it, but that's not really feasible given the current state of things.

**Comment by joe94** [comment]
Spoke to @ilawjr and sounds like it'll be a good idea to document this in our readme as a heads up.
