### ISSUE TITLE
identifier is a required field name

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#63]
argus no longer requires identifier as it should.  In previous builds it was required and the documentations states that it should be.

curl -i -H "Authorization: $basicauth" https://[argus-server]:443/api/v1/store/Joel2222 -d '{"data": {"year":1967,"words": ["What", "a", "Wonderful", "World"]},"ttl" : 300}' -X PUT -H "X-Midt-Owner: joel"
HTTP/1.1 200 OK
Content-Type: application/json
X-Midt-Server: argus
X-Midt-Version: 0.3.6
Date: Tue, 06 Oct 2020 23:24:20 GMT
Content-Length: 72
Connection: close
{"bucket":"Joel2222","id":"47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU"}

**Comment by joe94** [comment]
We are dropping this field per #78
