### ISSUE TITLE
Deleting resources with an owner

### ISSUE THREAD

**Issue by j-mai** [xmidt-org/argus#66]
Right now, a delete request without an owner header is able to delete resources that have an owner header. Is that what is wanted? Shouldn't it be that only the owner of the resource is allowed to delete it?

**Comment by JC000** [comment]
This is not the desired behavior.  Any resource created with an associated owner, must have access control to limit modifications to requests with the matching owner header.  Assume a request without a owner header to have an owner value of `null`.

**Comment by joe94** [comment]
This should be fixed now. Items owned by `X` should only be accessible to `X` and super users.
