### ISSUE TITLE
Info, Error, Debug loggers should not be stored

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/argus#75]
The following should not be created:
https://github.com/xmidt-org/argus/blob/402fede05764f2a0cd520b7495fb845ee4ebf372/chrysom/client.go#L65

**Comment by franszhafran** [comment]
Hello, thanks for opened an issue

Could you explain the reason why it should not be created?

**Comment by kcajmagic** [comment]
@franszhafran storing a logger to each level type while it may be convenient can make it harder to read the code and it is taking up extra space in memory that is little to no gain. It also makes it harder to maintain. What happens if we add another log level?
