### ISSUE TITLE
API change proposal

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#78]
1) **Change UUID field name to ID:** let's do this if we won't be enforcing this field to be an actual UUID.

2) **Drop the Identifier field**: unless there's a good reason for Argus to keep it, we should simply drop this and let users have it as part of their data payload.

3) **Drop explicit use of an AdminToken header for super user feature:** although the idea of a super user is still desired, the team proposed that information should be conveyed as part of the authentication token through `bascule`.
- JWTs: a capability could convey that information. 
- Basic Auth: perhaps a configurable allowList could help.

**Comment by JC000** [comment]
There is no reason why Argus can't enforce the primary identifier to be a true UUID.  Even if we choose to not use an UUID, Argus should still place constraints on what a valid value should look like (SHA256, MD5, etc).

**Comment by joe94** [comment]
True. What does each option give us? 
One route is to switch back to the ID field name and place the constraint that it must be a SHA256 checksum

**Comment by JC000** [comment]
Let's change the field name to `id`, but have strict enforcement that this field must be a 64 character long alpha-numeric string.  We can then suggest using SHA256 to generate this string.

**Comment by schmidtw** [comment]
So `id` is a string that matches the following regex: `[a-zA-Z0-9]{1,64}`

(1 to 64 ASCII alphanumeric characters)

Right?

**Comment by joe94** [comment]
That looks right to me.

**Comment by joe94** [comment]
Additional info: The webhooks library was sending a base64 URL encoding of the digest https://github.com/xmidt-org/webpa-common/blob/main/xwebhook/service.go#L89
If we add this, it should be easy to just send the digest itself.
