### ISSUE TITLE
Owner shouldn't change after item creation

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/argus#87]
The `authorized()` check allows super users to bypass a check if the item owner provided in the request matches the owner stored:
https://github.com/xmidt-org/argus/blob/16019f452b00f4287a86e6d3cc3e15612370d1be/store/endpoint.go#L111

In the set endpoint, we push this item:
https://github.com/xmidt-org/argus/blob/16019f452b00f4287a86e6d3cc3e15612370d1be/store/endpoint.go#L100
which is set up in transport:
https://github.com/xmidt-org/argus/blob/main/store/transport.go#L115

For normal users, the owners have to match so it's not an issue.  But because super users bypass this check, it allows them to modify the owner field.  My suggested fix is to check or overwrite any fields we don't want to change after getting the item already stored.

A few questions:
- If a super user provides an owner and it doesn't match the item there, do we fix the item they want to store or return a non-200 status?
- Are there any other fields that shouldn't be modified?

**Comment by joe94** [comment]
From team conversations, it seems that the consencus was to allow super users to update all fields of an item except its ownership and of course its ID. Essentially the owner header is ignore in super user mode for item update.

**Comment by joe94** [comment]
@JC000 @schmidtw do we foresee any use case to having super users update the owner of items they don't own?

**Comment by joe94** [comment]
Just checked and this is still a bug in main. I'm leaving a comment in the code with this issue number. I'll address this next.
