### ISSUE TITLE
Group scattered configuration components related to authentication

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#92]
### Context
Currently, our services all share very similar config and setup code for authentication. However, the configuration keys are sometimes different and there's not an easy to tell how the keys relate to each other besides the comments we added to the sample yaml files. It also makes it a bit more challenging to have shared setup code that works for all different services.

Since Argus is still at an early stage, this might be a good time to try a new structure at least for all values related to authentication. 

### Suggested idea
The suggested structure stems from the idea that authentication can be both inbound (authenticating incoming requests) and outbound (obtaining credentials to access external services). For inbound authentication, we've mostly been working with basic and bearer types but there is no limitation in adding new ones. For outbound authentication, although it seems a bit open form, the tool or service we are trying to access often determines which credential needs to be used.

More concretely, take a look at the current and suggested structures:

**Current configuration structure**
https://github.com/xmidt-org/argus/blob/c047e2109c67a06be48e3bccc94c42bb9150e99d/argus.yaml#L112

**Suggested structure:**
https://github.com/xmidt-org/argus/blob/9f7c5a2e7fc2ed9c733783c8311f2330284ee14d/argus.yaml#L110

### Benefits:
- Our config files will be easier to visually digest and understand the relationship between different config values related to authentication. For example, one no longer needs to rely as much on the comments to understand that `capabilityChecks`, `authHeader` and `jwtValidator` are all part of the same authentication process.
- For inbound authentication, it might make it easier to write bascule helper methods to create validators that work across different services. It'll remove some duplicated code. 

### Challenges:
- The config is less flat than current one. 
- It will be a big change if we wanted to propagate to all existing services. However, we could make it the standard for new services. @kristinaspring mentioned that this is also compatible with some of our newer internal services.

**Comment by joe94** [comment]
Kudos to @kristinaspring for helping review the structure and providing the great suggestion for outbound credentials to be keyed on the tool/service name! 🎆

**Comment by schmidtw** [comment]
I like your proposal @joe94.  The use of structure helps convey meaning as well as grouping.  Ideally I think it would be a big win to structure our code similarly.

Let's do it!

**Comment by joe94** [comment]
From team discussions, it sounded that we want something closer to the structure here https://gist.github.com/joe94/4e46fcbda12f310399d1cc7ad042242e. @johnabass suggested that this, alongside uber/fx and glue code, should help create a more explicit link between the bascule auth config and the server handlers they should apply to. 

From a quick review of the code, it looks like one option is extending authChainOut https://github.com/xmidt-org/argus/blob/main/auth.go#L89

to something like: 

```
type AuthChainOut struct {
	fx.Out
	Primary *alice.Chain `name:"servers.primary.auth"`
}
```

and then in here https://github.com/xmidt-org/argus/blob/main/auth.go#L103
walk through the different bascule "profiles" to instantiate the right field in AuthChainOut. This would require us to add a `server` or `profile` label to these measures https://github.com/xmidt-org/argus/blob/main/auth.go#L98

**Comment by johnabass** [comment]
That's basically the approach I was thinking.

FYI: You don't need `Primary` to be a pointer.  Just output an empty `Chain`, which is functionally equivalent to `nil`.  When injecting a `Chain`, just use `optional:"true"` and ignore whether it was actually injected.  Since the zero value of a `Chain` is valid and results in no decoration, this simplifies code quite a bit.

**Comment by joe94** [comment]
This work seems rather large to get into one PR so I'm breaking down into smaller parts #97, #98 and #99
